checks:
    php: true

filter:
    excluded_paths:
        - tests/*
        - vendor/*

build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=cover'
                coverage:
                    file: 'cover'
                    format: 'php-clover'